-- AlterTable
ALTER TABLE "User" ADD COLUMN     "canLogin" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "jwtExpiration" INTEGER NOT NULL DEFAULT 3600,
ALTER COLUMN "lastLogin" SET DEFAULT CURRENT_TIMESTAMP;
